### ISSUE TITLE
CVCalendar view not updating during screen rotation

### ISSUE THREAD

**Issue by RyanHop3** [CVCalendar/CVCalendar#436] opened 2017-03-15 18:17 UTC
I have situationally coded whether the calendar should appear as weekView or monthView based on the device:

    `func presentationMode() -> CalendarMode {
        let isLandscape: Bool = UIDevice.current.orientation.isLandscape
            
        if  isLandscape == true {
            return.weekView
        } else {
                return .monthView
        }
    }

    override func viewWillTransition(to size: CGSize, with coordinator:     UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        
        self.calendarView.calendarMode = self.presentationMode()
        self.calendarView.commitCalendarViewUpdate()
        menuView.commitMenuViewUpdate()
                
        }
    

    `
However when the build is run and the device is rotated to landscape, the calendar switches to weekView, but the day circles within the view do not change place and are off the view to the bottom (see photos).

If there another way to update the view so the day circles/ dates appear in the correct place?
<img width="376" alt="screen shot 2017-03-15 at 21 55 50" src="https://cloud.githubusercontent.com/assets/19892764/23963467/cef2348e-09ca-11e7-8671-7b702d6dceeb.png">
<img width="666" alt="screen shot 2017-03-15 at 21 56 02" src="https://cloud.githubusercontent.com/assets/19892764/23963469/d09574fe-09ca-11e7-9635-12637e3ca666.png">

**Comment by elsesiy** [comment] 2018-03-08 07:11
Duplicate of #441 and related to #485

**Closed by elsesiy** 2018-03-08 07:11 UTC
