### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by sategroup** [CVCalendar/CVCalendar#450] opened 2017-06-04 12:29 UTC
CVCalendar has memory leak on showing Calendar dates and leak count increases further on date selection
 
Environment:
Xcode 8.3.2
Swift 3
iPhone 6 (simulator & real device)

![screen shot 2017-06-04 at 5 56 01 pm](https://cloud.githubusercontent.com/assets/22125245/26761562/47e0b302-494f-11e7-8ac7-5ecb2ba41da8.png)

**Comment by elsesiy** [comment] 2017-06-04 18:15
Duplicate of #427, please use issue template in the future.

**Closed by elsesiy** 2017-06-04 18:15 UTC
