### ISSUE TITLE
Don't have a CircleView on the start

### ISSUE THREAD

**Issue by Kileren** [CVCalendar/CVCalendar#440] opened 2017-04-06 13:47 UTC
I have used CVCalendar before and everything was good, but after updating my Xcode to version 8.3 at the start of the project the current day doesn't have a CircleView around it and if the background is white it seems like that:
<img width="311" alt="2017-04-06 16 41 18" src="https://cloud.githubusercontent.com/assets/25293467/24757518/2222845a-1ae8-11e7-9a5a-68ec11eb1404.png">

But after tapping on any other day everything goes right.
<img width="310" alt="2017-04-06 16 41 34" src="https://cloud.githubusercontent.com/assets/25293467/24757524/27164a32-1ae8-11e7-8f8f-13b567a7792d.png">

<img width="311" alt="2017-04-06 16 46 09" src="https://cloud.githubusercontent.com/assets/25293467/24757671/9084782c-1ae8-11e7-8244-41fa76cf5a06.png">

**Comment by Nitner0C** [comment] 2017-04-07 08:30
Same issue here.

**Comment by thakurkrishna1991** [comment] 2017-04-10 06:06
same issue here.

**Comment by elsesiy** [comment] 2017-04-10 13:25
Thanks for reporting. Which version of the calendar do you use? Does it only happen in the simulator or also on a device? Please use the issue template to provide the necessary information.

**Comment by daichi1021** [comment] 2017-04-11 08:55
Same issue here.
CVCalendar1.5.0

**Comment by elsesiy** [comment] 2017-04-11 15:40
I looked into it but can't reproduce it. Please check the current example which is working fine or provide a demo project, thanks!

**Comment by joshuapong23** [comment] 2017-04-13 07:48
Same issue here.

**Comment by olivierbernal** [comment] 2017-04-13 22:13
Same here :)

**Comment by olivierbernal** [comment] 2017-04-13 23:04
A quick dirty fix: 

override func viewDidAppear(_ animated: Bool) {
DispatchQueue.main.asyncAfter(deadline: DispatchTime.init(uptimeNanoseconds: 100000000)) {
            self.calendarView.toggleViewWithDate(Date.init(timeIntervalSinceNow: -60000))
            self.calendarView.toggleCurrentDayView()
        }
}

**Comment by elsesiy** [comment] 2017-04-14 01:24
Can some of the reporters please validate that it's also not working in the demo as I'm not able to reproduce it.

**Comment by joshuapong23** [comment] 2017-04-14 14:49
My problem was simply because the background was white too.. All I needed to do was change the appearance 👍

**Comment by edwinruan** [comment] 2017-04-14 19:49
Same issue happened me. Looking like, the `toggleCurrentDayView()` do not work if `presentedDate` is today.  
![1](https://cloud.githubusercontent.com/assets/14810193/25054140/157f3df8-2121-11e7-9692-d61c7b93e2f9.png)
![2](https://cloud.githubusercontent.com/assets/14810193/25054240/9ac3a71a-2121-11e7-9eb0-6dfd629324e9.png)

 You can see from the second. The text is changed to white when highlighted but the circle view is not shown. Tapping on current Date won't work.  Has to tap another date and tap back.

**Comment by RSickenberg** [comment] 2017-04-19 13:35
Same issue

**Comment by elsesiy** [comment] 2017-05-13 12:44
Maybe @joshuapong23 can help @edwinruan and @RSickenberg if there's still help needed. I'll close this for now, as I'm not able to reproduce it.

**Closed by elsesiy** 2017-05-13 12:44 UTC

**Comment by RSickenberg** [comment] 2017-10-17 17:03
Can you please reopen the issue, I still have it :-/ 
![image](https://user-images.githubusercontent.com/16922548/31678234-cf279b18-b36d-11e7-840b-c36b2b805b1a.png)
